#!/usr/bin/env bash

## Web-based script to initialize Docksal powered Drupal 7 site
## Usage:
##   fin exec-url https://raw.githubusercontent.com/docksal/drupal7/master/.docksal/commands/web-init

# Abort if anything fails
set -e

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[1;33m'
NC='\033[0m'

_name_project ()
{
	while true; do
		read -p "$1: " projectName
		break
	done
}

# Yes/no confirmation dialog with an optional message
# @param $1 confirmation message
_confirm ()
{
	while true; do
		read -p "$1 [y/n]: " answer
		case ${answer} in
			[Yy]|[Yy][Ee][Ss] )
				break
				;;
			[Nn]|[Nn][Oo] )
				exit 1
				;;
			* )
				echo 'Please answer yes or no.'
		esac
	done
}

echo -e "${green}Docksal powered Drupal 7 project setup${NC}"
echo "------------------------------------------------"
_name_project "Please enter the name of your project"
echo -e "Preparing to download Drupal 7 project to ${yellow}$(pwd)/${projectName}${NC}"
_confirm "Continue with this folder?"
echo -e "${green_bg} INIT ${NC}${green} Cloning repository...${NC}"

git clone -b master https://github.com/docksal/drupal7.git ${projectName}
cd ${projectName}/.docksal

# We have to do this sed command twice, to account for lines with more than
# one occurence of "drupal7.docksal"
sed -i.bak "s/drupal7/${projectName}/" docksal.env
rm docksal.env.bak > /dev/null 2>&1
sed -i.bak "s/drupal7/${projectName}/" docksal.env
rm docksal.env.bak > /dev/null 2>&1
cd ..

fin init
